version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=gloria_2007
      - DATABASE_NAME=task_management
      - JWT_SECRET=42ee10b3fa6518b9238145268173e8509b4741eb

    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gloria_@2007
      - POSTGRES_DB=task_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: